// productos.js
const items = [
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Medellín - Apartamento, Laureles",
    price: "Arriendo - $185.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Bogotá - Casa, Chapinero",
    price: "Desde $350.000.000 - Hasta $450.000.000",
    area: "Área m² 200",
    rooms: "Habit. 3",
    baths: "Baños 2",
    badge: "alta demanda",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Cali - Apartamento, El Peñón",
    price: "Arriendo - $150.000.000",
    area: "Área m² 90",
    rooms: "Habit. 2",
    baths: "Baños 1",
    badge: "nuevo",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Cartagena - Casa, Bocagrande",
    price: "Arriendo - $400.000.000",
    area: "Área m² 250",
    rooms: "Habit. 4",
    baths: "Baños 3",
    badge: "destacado",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Barranquilla - Apartamento, Villa Santos",
    price: "Arriendo - $280.000.000",
    area: "Área m² 120",
    rooms: "Habit. 2",
    baths: "Baños 2",
    badge: "nuevo",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Pereira - Casa, La Virginia",
    price: "Arriendo - $200.000.000",
    area: "Área m² 150",
    rooms: "Habit. 3",
    baths: "Baños 2",
    badge: "alta demanda",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Bucaramanga - Apartamento, Cabecera",
    price: "Arriendo - $220.000.000",
    area: "Área m² 110",
    rooms: "Habit. 2",
    baths: "Baños 1",
    badge: "nuevo",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Manizales - Casa, El Cable",
    price: "Arriendo - $160.000.000",
    area: "Área m² 100",
    rooms: "Habit. 2",
    baths: "Baños 1",
    badge: "destacado",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Cali - Casa, Ciudad Jardín",
    price: "Arriendo - $300.000.000",
    area: "Área m² 180",
    rooms: "Habit. 3",
    baths: "Baños 2",
    badge: "alta demanda",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Medellín - Apartamento, El Poblado",
    price: "Arriendo - $600.000.000",
    area: "Área m² 200",
    rooms: "Habit. 3",
    baths: "Baños 3",
    badge: "nuevo",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Bogotá - Apartamento, Usaquén",
    price: "Arriendo - $450.000.000",
    area: "Área m² 140",
    rooms: "Habit. 2",
    baths: "Baños 2",
    badge: "destacado",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Cali - Casa, San Fernando",
    price: "Arriendo - $220.000.000",
    area: "Área m² 130",
    rooms: "Habit. 3",
    baths: "Baños 2",
    badge: "nuevo",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Medellín - Apartamento, Laureles",
    price: "Arriendo - $185.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Bogotá - Casa, Chapinero",
    price: "Desde $350.000.000 - Hasta $450.000.000",
    area: "Área m² 200",
    rooms: "Habit. 3",
    baths: "Baños 2",
    badge: "alta demanda",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Cali - Apartamento, El Peñón",
    price: "Arriendo - $150.000.000",
    area: "Área m² 90",
    rooms: "Habit. 2",
    baths: "Baños 1",
    badge: "nuevo",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Cartagena - Casa, Bocagrande",
    price: "Arriendo - $400.000.000",
    area: "Área m² 250",
    rooms: "Habit. 4",
    baths: "Baños 3",
    badge: "destacado",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Barranquilla - Apartamento, Villa Santos",
    price: "Arriendo - $280.000.000",
    area: "Área m² 120",
    rooms: "Habit. 2",
    baths: "Baños 2",
    badge: "nuevo",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Pereira - Casa, La Virginia",
    price: "Arriendo - $200.000.000",
    area: "Área m² 150",
    rooms: "Habit. 3",
    baths: "Baños 2",
    badge: "alta demanda",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Bucaramanga - Apartamento, Cabecera",
    price: "Arriendo - $220.000.000",
    area: "Área m² 110",
    rooms: "Habit. 2",
    baths: "Baños 1",
    badge: "nuevo",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Manizales - Casa, El Cable",
    price: "Arriendo - $160.000.000",
    area: "Área m² 100",
    rooms: "Habit. 2",
    baths: "Baños 1",
    badge: "destacado",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Cali - Casa, Ciudad Jardín",
    price: "Arriendo - $300.000.000",
    area: "Área m² 180",
    rooms: "Habit. 3",
    baths: "Baños 2",
    badge: "alta demanda",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Medellín - Apartamento, El Poblado",
    price: "Arriendo - $600.000.000",
    area: "Área m² 200",
    rooms: "Habit. 3",
    baths: "Baños 3",
    badge: "nuevo",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Bogotá - Apartamento, Usaquén",
    price: "Arriendo - $450.000.000",
    area: "Área m² 140",
    rooms: "Habit. 2",
    baths: "Baños 2",
    badge: "destacado",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Cali - Casa, San Fernando",
    price: "Arriendo - $220.000.000",
    area: "Área m² 130",
    rooms: "Habit. 3",
    baths: "Baños 2",
    badge: "nuevo",
  },    {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Medellín - Apartamento, Laureles",
    price: "Arriendo - $185.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Bogotá - Casa, Chapinero",
    price: "Desde $350.000.000 - Hasta $450.000.000",
    area: "Área m² 200",
    rooms: "Habit. 3",
    baths: "Baños 2",
    badge: "alta demanda",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Cali - Apartamento, El Peñón",
    price: "Arriendo - $150.000.000",
    area: "Área m² 90",
    rooms: "Habit. 2",
    baths: "Baños 1",
    badge: "nuevo",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Cartagena - Casa, Bocagrande",
    price: "Arriendo - $400.000.000",
    area: "Área m² 250",
    rooms: "Habit. 4",
    baths: "Baños 3",
    badge: "destacado",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Barranquilla - Apartamento, Villa Santos",
    price: "Arriendo - $280.000.000",
    area: "Área m² 120",
    rooms: "Habit. 2",
    baths: "Baños 2",
    badge: "nuevo",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Pereira - Casa, La Virginia",
    price: "Arriendo - $200.000.000",
    area: "Área m² 150",
    rooms: "Habit. 3",
    baths: "Baños 2",
    badge: "alta demanda",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Bucaramanga - Apartamento, Cabecera",
    price: "Arriendo - $220.000.000",
    area: "Área m² 110",
    rooms: "Habit. 2",
    baths: "Baños 1",
    badge: "nuevo",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Manizales - Casa, El Cable",
    price: "Arriendo - $160.000.000",
    area: "Área m² 100",
    rooms: "Habit. 2",
    baths: "Baños 1",
    badge: "destacado",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Cali - Casa, Ciudad Jardín",
    price: "Arriendo - $300.000.000",
    area: "Área m² 180",
    rooms: "Habit. 3",
    baths: "Baños 2",
    badge: "alta demanda",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Medellín - Apartamento, El Poblado",
    price: "Arriendo - $600.000.000",
    area: "Área m² 200",
    rooms: "Habit. 3",
    baths: "Baños 3",
    badge: "nuevo",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Bogotá - Apartamento, Usaquén",
    price: "Arriendo - $450.000.000",
    area: "Área m² 140",
    rooms: "Habit. 2",
    baths: "Baños 2",
    badge: "destacado",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Cali - Casa, San Fernando",
    price: "Arriendo - $220.000.000",
    area: "Área m² 130",
    rooms: "Habit. 3",
    baths: "Baños 2",
    badge: "nuevo",
  },    {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Medellín - Apartamento, Laureles",
    price: "Arriendo - $185.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Bogotá - Casa, Chapinero",
    price: "Desde $350.000.000 - Hasta $450.000.000",
    area: "Área m² 200",
    rooms: "Habit. 3",
    baths: "Baños 2",
    badge: "alta demanda",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Cali - Apartamento, El Peñón",
    price: "Arriendo - $150.000.000",
    area: "Área m² 90",
    rooms: "Habit. 2",
    baths: "Baños 1",
    badge: "nuevo",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Cartagena - Casa, Bocagrande",
    price: "Arriendo - $400.000.000",
    area: "Área m² 250",
    rooms: "Habit. 4",
    baths: "Baños 3",
    badge: "destacado",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Barranquilla - Apartamento, Villa Santos",
    price: "Arriendo - $280.000.000",
    area: "Área m² 120",
    rooms: "Habit. 2",
    baths: "Baños 2",
    badge: "nuevo",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Pereira - Casa, La Virginia",
    price: "Arriendo - $200.000.000",
    area: "Área m² 150",
    rooms: "Habit. 3",
    baths: "Baños 2",
    badge: "alta demanda",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Bucaramanga - Apartamento, Cabecera",
    price: "Arriendo - $220.000.000",
    area: "Área m² 110",
    rooms: "Habit. 2",
    baths: "Baños 1",
    badge: "nuevo",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Manizales - Casa, El Cable",
    price: "Arriendo - $160.000.000",
    area: "Área m² 100",
    rooms: "Habit. 2",
    baths: "Baños 1",
    badge: "destacado",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Cali - Casa, Ciudad Jardín",
    price: "Arriendo - $300.000.000",
    area: "Área m² 180",
    rooms: "Habit. 3",
    baths: "Baños 2",
    badge: "alta demanda",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Medellín - Apartamento, El Poblado",
    price: "Arriendo - $600.000.000",
    area: "Área m² 200",
    rooms: "Habit. 3",
    baths: "Baños 3",
    badge: "nuevo",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Bogotá - Apartamento, Usaquén",
    price: "Arriendo - $450.000.000",
    area: "Área m² 140",
    rooms: "Habit. 2",
    baths: "Baños 2",
    badge: "destacado",
  },
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Cali - Casa, San Fernando",
    price: "Arriendo - $220.000.000",
    area: "Área m² 130",
    rooms: "Habit. 3",
    baths: "Baños 2",
    badge: "nuevo",
  },
  ,
  {
    imgSrc: "https://via.placeholder.com/300x200",
    info: "Cali - Casa, San Fernando",
    price: "Arriendo - $220.000.000",
    area: "Área m² 130",
    rooms: "Habit. 3",
    baths: "Baños 2",
    badge: "nuevo",
  },
];
  
  export default items;
  