// productos.js
const items = [
  {
    imgSrc: "/img/Destacados/img-d-1.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Arriendo - $185.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "",
    nuevo: false,
    proyecto: false,
  },
  {
    imgSrc: "/img/Destacados/img-d-1.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Desde $185.000.000 - Hasta $255.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "destacado",
    nuevo: true,
    proyecto: true,
  },
  {
    imgSrc: "/img/Destacados/img-d-1.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Arriendo - $185.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "",
    nuevo: false,
    proyecto: false,
  },
  {
    imgSrc: "/img/Destacados/img-d-2.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Desde $185.000.000 - Hasta $255.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "",
    nuevo: false,
    proyecto: false,
  },
  {
    imgSrc: "/img/Destacados/img-d-1.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Arriendo - $185.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "",
    nuevo: true,
    proyecto: false,
  },
  {
    imgSrc: "/img/Destacados/img-d-2.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Desde $185.000.000 - Hasta $255.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "",
    nuevo: false,
    proyecto: false,
  },
  {
    imgSrc: "/img/Destacados/img-d-1.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Arriendo - $185.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "destacado",
    nuevo: false,
    proyecto: true,
  },
  {
    imgSrc: "/img/Destacados/img-d-1.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Desde $185.000.000 - Hasta $255.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "alta demanda",
    nuevo: false,
    proyecto: false,
  },
  {
    imgSrc: "/img/Destacados/img-d-1.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Arriendo - $185.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "destacado",
    nuevo: false,
    proyecto: true,
  },
  {
    imgSrc: "/img/Destacados/img-d-2.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Desde $185.000.000 - Hasta $255.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "",
    nuevo: false,
    proyecto: true,
  },
  {
    imgSrc: "/img/Destacados/img-d-1.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Arriendo - $185.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "alta demanda",
    nuevo: false,
    proyecto: false,
  },
  {
    imgSrc: "/img/Destacados/img-d-2.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Desde $185.000.000 - Hasta $255.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "",
    nuevo: false,
    proyecto: true,
  },
  {
    imgSrc: "/img/Destacados/img-d-1.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Arriendo - $185.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "destacado",
    nuevo: true,
    proyecto: false,
  },
  {
    imgSrc: "/img/Destacados/img-d-1.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Desde $185.000.000 - Hasta $255.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "destacado",
    nuevo: true,
    proyecto: true,
  },
  {
    imgSrc: "/img/Destacados/img-d-1.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Arriendo - $185.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "destacado",
    nuevo: true,
    proyecto: false,
  },
  {
    imgSrc: "/img/Destacados/img-d-2.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Desde $185.000.000 - Hasta $255.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "destacado",
    nuevo: true,
    proyecto: true,
  },
  {
    imgSrc: "/img/Destacados/img-d-1.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Arriendo - $185.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "destacado",
    nuevo: true,
    proyecto: false,
  },
  {
    imgSrc: "/img/Destacados/img-d-2.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Desde $185.000.000 - Hasta $255.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "destacado",
    nuevo: true,
    proyecto: true,
  },
  {
    imgSrc: "/img/Destacados/img-d-1.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Arriendo - $185.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "destacado",
    nuevo: true,
    proyecto: false,
  },
  {
    imgSrc: "/img/Destacados/img-d-1.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Desde $185.000.000 - Hasta $255.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "destacado",
    nuevo: true,
    proyecto: true,
  },
  {
    imgSrc: "/img/Destacados/img-d-1.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Arriendo - $185.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "destacado",
    nuevo: true,
    proyecto: false,
  },
  {
    imgSrc: "/img/Destacados/img-d-2.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Desde $185.000.000 - Hasta $255.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "destacado",
    nuevo: true,
    proyecto: true,
  },
  {
    imgSrc: "/img/Destacados/img-d-1.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Arriendo - $185.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "destacado",
    nuevo: true,
    proyecto: false,
  },
  {
    imgSrc: "/img/Destacados/img-d-2.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Desde $185.000.000 - Hasta $255.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "destacado",
    nuevo: true,
    proyecto: true,
  },
  {
    imgSrc: "/img/Destacados/img-d-1.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Arriendo - $185.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "destacado",
    nuevo: true,
    proyecto: false,
  },
  {
    imgSrc: "/img/Destacados/img-d-1.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Desde $185.000.000 - Hasta $255.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "destacado",
    nuevo: true,
    proyecto: true,
  },
  {
    imgSrc: "/img/Destacados/img-d-1.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Arriendo - $185.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "destacado",
    nuevo: true,
    proyecto: false,
  },
  {
    imgSrc: "/img/Destacados/img-d-2.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Desde $185.000.000 - Hasta $255.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "destacado",
    nuevo: true,
    proyecto: true,
  },
  {
    imgSrc: "/img/Destacados/img-d-1.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Arriendo - $185.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "destacado",
    nuevo: true,
    proyecto: false,
  },
  {
    imgSrc: "/img/Destacados/img-d-2.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Desde $185.000.000 - Hasta $255.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "destacado",
    nuevo: true,
    proyecto: true,
  },
  {
    imgSrc: "/img/Destacados/img-d-1.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Arriendo - $185.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "destacado",
    nuevo: true,
    proyecto: false,
  },
  {
    imgSrc: "/img/Destacados/img-d-1.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Desde $185.000.000 - Hasta $255.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "destacado",
    nuevo: true,
    proyecto: true,
  },
  {
    imgSrc: "/img/Destacados/img-d-1.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Arriendo - $185.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "destacado",
    nuevo: true,
    proyecto: false,
  },
  {
    imgSrc: "/img/Destacados/img-d-2.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Desde $185.000.000 - Hasta $255.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "destacado",
    nuevo: true,
    proyecto: true,
  },
  {
    imgSrc: "/img/Destacados/img-d-1.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Arriendo - $185.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "destacado",
    nuevo: true,
    proyecto: false,
  },
  {
    imgSrc: "/img/Destacados/img-d-2.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Desde $185.000.000 - Hasta $255.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "destacado",
    nuevo: true,
    proyecto: true,
  },
  {
    imgSrc: "/img/Destacados/img-d-1.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Arriendo - $185.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "destacado",
    nuevo: true,
    proyecto: false,
  },
  {
    imgSrc: "/img/Destacados/img-d-1.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Desde $185.000.000 - Hasta $255.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "destacado",
    nuevo: true,
    proyecto: true,
  },
  {
    imgSrc: "/img/Destacados/img-d-1.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Arriendo - $185.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "destacado",
    nuevo: true,
    proyecto: false,
  },
  {
    imgSrc: "/img/Destacados/img-d-2.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Desde $185.000.000 - Hasta $255.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "destacado",
    nuevo: true,
    proyecto: true,
  },
  {
    imgSrc: "/img/Destacados/img-d-1.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Arriendo - $185.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "destacado",
    nuevo: true,
    proyecto: false,
  },
  {
    imgSrc: "/img/Destacados/img-d-2.png",
    info: "Bogotá - Apartaestudio, Chapinero alto",
    price: "Desde $185.000.000 - Hasta $255.000.000",
    area: "Área m² 132",
    rooms: "Habit. 1",
    baths: "Baños 1",
    badge: "destacado",
    nuevo: true,
    proyecto: true,
  },
];
  
  export default items;
  